'use strict'

export const SIGNUP = {
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SIGNUP_RESULT: 'SIGNUP_RESULT',
}
export const SIGNIN = {
  SIGNIN_RESULT: 'SIGNIN_RESULT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
}
export const POST = {
  CREATE_RESULT: 'CREATE_RESULT',
}

export default { SIGNUP, SIGNIN }